import Head from "next/head";
import Navbar from"../components/Navbar";
import Footer from"../components/Footer";
import HomePage from "./HomePage";
import Services from "./Services";
import Contact from "./Contact"
import pro from "./public/images/pro.jpg";

import { MdContactMail } from "react-icons/md";
import Works from "./works";
export default function Home () {
  return (
    <div>
      <Head>
        <title>ZAHIR-Electro-Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.jpg" />
      </Head>
      <Navbar />
      <HomePage />
      
      <Services />
      <Works/>
      <Contact />
      <Footer />
      
         </div>
  );
}
